services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb-hours
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - gym-app-network

  trainer-hours-app:
    build: .
    container_name: trainer-hours-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - gym-app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-hours
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
    depends_on:
      - mongodb
    networks:
      - gym-app-network

networks:
  gym-app-network:
    external: true

volumes:
  mongodb_data:
