services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - gym-app-network	
networks:
   gym-app-network:
    external: true

volumes:
  mongodb_data:
