spring:
  kafka:
    consumer:
      bootstrap-servers: noop:0
      auto-startup: false
    listener:
      auto-startup: false
    admin:
      auto-create: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

eureka:
  client:
    enabled: false
